#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

#define MIN(a,b) (((a)<(b))?(a):(b))
#define ADD(a,b) (a + b)

/*
Concretely, the traces generated by SGXTracer in Section 2.4 should be the same for all
pairs of guesses of the same length and correct passwords of any length.
For example, traces for the pairs of guess and correct passwords (magic, magicbeans), (qwert,
qwerty), and (pawnd, magic) should be identical because all guesses are 5 characters long.
The traces for (qwerty, qwerty), (magicbeans, magic), and (justmagic, magicbeans)
can be different because the length of the guesses differ.
*/

int check_password(char* p, char* i, int i_size) {
	/*
	The hcorrecti password in this file is padded with dollars ($) on both sides using the following
	scheme: the first 15 − l $s followed by l characters of the correct password, followed by 15 − l
	$s. For example, if the correct password is magicbeans, the file will contain
	$$$$$magicbeans$$$$$.
	*/
	// Do the same to the guess

	// Now do the comparision
	int k = 0;
	int max_length = 15; //check always over all 15 chars
	int pos = 0;
	for (pos = 0; pos < max_length; pos++)	{
		if (p[pos] == i[pos]) {
			k++;
		}
	}

	if (k == 15)
		return 1;
	else 
		return 0;

}

//assumptions: password only has small characters [a, z], maximum length is 15 characters
int main (int argc, char* argv[])	{

	if (argc != 3) {
		fprintf(stderr, "Usage: %s <password guess> <output_file>\n", argv[0]);
		exit(EXIT_FAILURE);
	}


	FILE* password_file;
	char password [16] = "\0";
	
	size_t len = 0;
	char* line;
	password_file = fopen ("/home/sgx/isl/t3_3/password.txt", "r");

	if (password_file == NULL) {
		perror("cannot open password file\n");
		exit(EXIT_FAILURE);
	}

	fscanf(password_file, "%s", password);

	int is_match = 0; 
	is_match = check_password(password, argv[1], strlen(argv[1]));
	
	FILE* output_file;
	output_file = fopen (argv[2], "wb");
	fputc(is_match, output_file);
	fclose(output_file);

	fclose(password_file);
	return 0;
}


